package panelView;

import Controller.CustomerControl;
import DAO.CustomerDAO;
import java.awt.Component;
import exception.InputKosongException;
import exception.InputHarusAngkaException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import Model.Customer;

public class CustomerMainPanel extends javax.swing.JPanel {

    private CustomerControl cc;
    private Customer c = null;
    String actionCustomer = null;

    private Component rootPane;
    private String selectedId = "";

    public CustomerMainPanel() {
        cc = new CustomerControl(new CustomerDAO());
        initComponents();
        setOpaque(false);
        showCustomer();
        setComponentsCustomer(false);
        idCustomerInputTextField.setEnabled(false); // langsung false saja karena rencananya id gak bisa di ubah
        setCustomerEditDeleteButton(false);
        clearText();
    }

    public void inputKosongPelangganException() throws InputKosongException {
        if (idCustomerInputTextField.getText().isEmpty() || namaCustomerInputTextfield.getText().isEmpty() || alamatInputTextField.getText().isEmpty() || nomorTeleponInputTextField.getText().isEmpty()) {
            throw new InputKosongException();
        }
    }

    private void InputHarusAngkaPelangganException() throws InputHarusAngkaException { // exception khusus untuk gaji
        if (!isFloat(nomorTeleponInputTextField.getText())) {
            throw new InputHarusAngkaException();
        }
    }
    
    private boolean isFloat(String input) {
        try {
            Float.parseFloat(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }


    public void setComponentsCustomer(boolean value) { // ngeset tempat input
        namaCustomerInputTextfield.setEnabled(value);
        nomorTeleponInputTextField.setEnabled(value);
        alamatInputTextField.setEnabled(value);
    }

    public void setCustomerEditDeleteButton(boolean value) { // membuka/tutup tombol barukan dan hapus jika mau/tidak mau ngedit data
        barukanCustomerButton.setEnabled(value);
        hapusCustomerButton.setEnabled(value);
    }

    public void clearText() {
        idCustomerInputTextField.setText("");
        namaCustomerInputTextfield.setText("");
        searchCustomerInputTextField.setText("");
        nomorTeleponInputTextField.setText("");
        alamatInputTextField.setText("");
        idCustomerInputTextField.setText("");
    }
    
    public void showCustomer(){
        tabelCustomer.setModel(cc.showTableBySearch(""));
        addHeaderClickListener(tabelCustomer);
    }

    private void doSearchPelanggan() { // fungsi untuk search dipakai di : searchKaryawanInputButtonActionPerformed
        if (searchCustomerInputTextField.getText().isEmpty()) {
            showCustomer();
            return;
        }
        tabelCustomer.setModel(cc.showTableBySearch(searchCustomerInputTextField.getText()));
        addHeaderClickListener(tabelCustomer);
    }

    private static void addHeaderClickListener(JTable table) {
        JTableHeader header = table.getTableHeader();
        header.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int col = header.columnAtPoint(e.getPoint());
            }
        });
        TableModel tableModel = table.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>((TableModel) tableModel);
        table.setRowSorter(sorter);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        mainPanel = new javax.swing.JPanel();
        searchCustomerInputPanel = new javax.swing.JPanel();
        searchCustomerInputLabel = new javax.swing.JLabel();
        searchCustomerInputTextField = new javax.swing.JTextField();
        searchCustomerInputButton = new javax.swing.JButton();
        CustomerFormPanel = new javax.swing.JPanel();
        CustomerButtonPanel = new javax.swing.JPanel();
        barukanCustomerButton = new javax.swing.JButton();
        hapusCustomerButton = new javax.swing.JButton();
        tambahCustomerButton = new javax.swing.JButton();
        idCustomerInputPanel = new javax.swing.JPanel();
        idCustomerInputLabel = new javax.swing.JLabel();
        idCustomerInputTextField = new javax.swing.JTextField();
        nomorTeleponInputPanel = new javax.swing.JPanel();
        nomorTeleponInputLabel = new javax.swing.JLabel();
        nomorTeleponInputTextField = new javax.swing.JTextField();
        namaCustomerInputPanel = new javax.swing.JPanel();
        namaCustomerInputLabel = new javax.swing.JLabel();
        namaCustomerInputTextfield = new javax.swing.JTextField();
        alamatInputPanel = new javax.swing.JPanel();
        alamatInputTextField = new javax.swing.JTextField();
        alamatInputLabel = new javax.swing.JLabel();
        simpanCustomerButton = new javax.swing.JButton();
        batalkanCustomerButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelCustomer = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(153, 153, 255));

        mainPanel.setBackground(new java.awt.Color(153, 153, 255));

        searchCustomerInputPanel.setBackground(new java.awt.Color(153, 153, 255));

        searchCustomerInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchCustomerInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        searchCustomerInputLabel.setText("Pencarian Customer");

        searchCustomerInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchCustomerInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchCustomerInputTextFieldKeyPressed(evt);
            }
        });

        searchCustomerInputButton.setBackground(new java.awt.Color(137, 92, 3));
        searchCustomerInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchCustomerInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchCustomerInputButton.setText("Cari");
        searchCustomerInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerInputButtonActionPerformed(evt);
            }
        });

        CustomerFormPanel.setBackground(new java.awt.Color(153, 153, 255));

        CustomerButtonPanel.setBackground(new java.awt.Color(153, 153, 255));

        barukanCustomerButton.setBackground(new java.awt.Color(255, 175, 47));
        barukanCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanCustomerButton.setText("Barukan");
        barukanCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanCustomerButtonActionPerformed(evt);
            }
        });

        hapusCustomerButton.setBackground(new java.awt.Color(237, 78, 5));
        hapusCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusCustomerButton.setText("Hapus");
        hapusCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusCustomerButtonActionPerformed(evt);
            }
        });

        tambahCustomerButton.setBackground(new java.awt.Color(51, 151, 56));
        tambahCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahCustomerButton.setText("Tambah");
        tambahCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomerButtonPanelLayout = new javax.swing.GroupLayout(CustomerButtonPanel);
        CustomerButtonPanel.setLayout(CustomerButtonPanelLayout);
        CustomerButtonPanelLayout.setHorizontalGroup(
            CustomerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahCustomerButton)
                .addGap(18, 18, 18)
                .addComponent(barukanCustomerButton)
                .addGap(18, 18, 18)
                .addComponent(hapusCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        CustomerButtonPanelLayout.setVerticalGroup(
            CustomerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idCustomerInputPanel.setBackground(new java.awt.Color(153, 153, 255));

        idCustomerInputLabel.setBackground(new java.awt.Color(0, 0, 0));
        idCustomerInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idCustomerInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        idCustomerInputLabel.setText("ID Customer");

        idCustomerInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout idCustomerInputPanelLayout = new javax.swing.GroupLayout(idCustomerInputPanel);
        idCustomerInputPanel.setLayout(idCustomerInputPanelLayout);
        idCustomerInputPanelLayout.setHorizontalGroup(
            idCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idCustomerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idCustomerInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(idCustomerInputPanelLayout.createSequentialGroup()
                        .addComponent(idCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        idCustomerInputPanelLayout.setVerticalGroup(
            idCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idCustomerInputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idCustomerInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nomorTeleponInputPanel.setBackground(new java.awt.Color(153, 153, 255));

        nomorTeleponInputLabel.setBackground(new java.awt.Color(0, 0, 0));
        nomorTeleponInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        nomorTeleponInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        nomorTeleponInputLabel.setText("Nomor Telepon");

        nomorTeleponInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout nomorTeleponInputPanelLayout = new javax.swing.GroupLayout(nomorTeleponInputPanel);
        nomorTeleponInputPanel.setLayout(nomorTeleponInputPanelLayout);
        nomorTeleponInputPanelLayout.setHorizontalGroup(
            nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorTeleponInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(nomorTeleponInputPanelLayout.createSequentialGroup()
                        .addComponent(nomorTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nomorTeleponInputPanelLayout.setVerticalGroup(
            nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponInputPanelLayout.createSequentialGroup()
                .addComponent(nomorTeleponInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomorTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        namaCustomerInputPanel.setBackground(new java.awt.Color(153, 153, 255));

        namaCustomerInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaCustomerInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        namaCustomerInputLabel.setText("Nama");

        namaCustomerInputTextfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaCustomerInputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namaCustomerInputTextfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout namaCustomerInputPanelLayout = new javax.swing.GroupLayout(namaCustomerInputPanel);
        namaCustomerInputPanel.setLayout(namaCustomerInputPanelLayout);
        namaCustomerInputPanelLayout.setHorizontalGroup(
            namaCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaCustomerInputPanelLayout.createSequentialGroup()
                .addGroup(namaCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namaCustomerInputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(namaCustomerInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(namaCustomerInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        namaCustomerInputPanelLayout.setVerticalGroup(
            namaCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaCustomerInputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namaCustomerInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaCustomerInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        alamatInputPanel.setBackground(new java.awt.Color(153, 153, 255));

        alamatInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        alamatInputLabel.setBackground(new java.awt.Color(0, 0, 0));
        alamatInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        alamatInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        alamatInputLabel.setText("Alamat");

        javax.swing.GroupLayout alamatInputPanelLayout = new javax.swing.GroupLayout(alamatInputPanel);
        alamatInputPanel.setLayout(alamatInputPanelLayout);
        alamatInputPanelLayout.setHorizontalGroup(
            alamatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alamatInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(alamatInputPanelLayout.createSequentialGroup()
                .addComponent(alamatInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        alamatInputPanelLayout.setVerticalGroup(
            alamatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alamatInputPanelLayout.createSequentialGroup()
                .addComponent(alamatInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alamatInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout CustomerFormPanelLayout = new javax.swing.GroupLayout(CustomerFormPanel);
        CustomerFormPanel.setLayout(CustomerFormPanelLayout);
        CustomerFormPanelLayout.setHorizontalGroup(
            CustomerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerFormPanelLayout.createSequentialGroup()
                        .addComponent(CustomerButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 350, Short.MAX_VALUE))
                    .addGroup(CustomerFormPanelLayout.createSequentialGroup()
                        .addGroup(CustomerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomorTeleponInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idCustomerInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(CustomerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaCustomerInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(CustomerFormPanelLayout.createSequentialGroup()
                                .addComponent(alamatInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        CustomerFormPanelLayout.setVerticalGroup(
            CustomerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomerButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CustomerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idCustomerInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaCustomerInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CustomerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorTeleponInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpanCustomerButton.setBackground(new java.awt.Color(51, 151, 56));
        simpanCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanCustomerButton.setText("Simpan");
        simpanCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanCustomerButtonActionPerformed(evt);
            }
        });

        batalkanCustomerButton.setBackground(new java.awt.Color(237, 78, 5));
        batalkanCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        batalkanCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        batalkanCustomerButton.setText("Batalkan");
        batalkanCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batalkanCustomerButtonMouseClicked(evt);
            }
        });
        batalkanCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalkanCustomerButtonActionPerformed(evt);
            }
        });

        tabelCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pelanggan", "Nama Pelanggan", "Nomor Telepon", "Alamat"
            }
        ));
        tabelCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelCustomer);

        javax.swing.GroupLayout searchCustomerInputPanelLayout = new javax.swing.GroupLayout(searchCustomerInputPanel);
        searchCustomerInputPanel.setLayout(searchCustomerInputPanelLayout);
        searchCustomerInputPanelLayout.setHorizontalGroup(
            searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                .addGroup(searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchCustomerInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                                .addComponent(searchCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchCustomerInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 549, Short.MAX_VALUE))))
                    .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                        .addComponent(CustomerFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                        .addComponent(batalkanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        searchCustomerInputPanelLayout.setVerticalGroup(
            searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCustomerInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchCustomerInputTextField)
                    .addComponent(searchCustomerInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGroup(searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batalkanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simpanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchCustomerInputPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCustomerInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCustomerInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchCustomerInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchCustomerInputTextFieldKeyPressed

    }//GEN-LAST:event_searchCustomerInputTextFieldKeyPressed

    private void searchCustomerInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerInputButtonActionPerformed
        doSearchPelanggan();
    }//GEN-LAST:event_searchCustomerInputButtonActionPerformed

    private void barukanCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanCustomerButtonActionPerformed
        actionCustomer = "update"; 
        setComponentsCustomer(true); // membuka akses field input
    }//GEN-LAST:event_barukanCustomerButtonActionPerformed

    private void hapusCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusCustomerButtonActionPerformed
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION) {
            return;
        }

        cc.delete(idCustomerInputTextField.getText()); // delete berdasarkan id
        clearText(); // bersihin field input
        tambahCustomerButton.setEnabled(true);
        setCustomerEditDeleteButton(false); 
        setComponentsCustomer(false); // tutup field input
        showCustomer(); // melakukan show ulang
    }//GEN-LAST:event_hapusCustomerButtonActionPerformed

    private void tambahCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahCustomerButtonActionPerformed
        actionCustomer = "add";
        clearText(); // bersihin field input
        setCustomerEditDeleteButton(false); // membatasi tombol edit dan hapus
        setComponentsCustomer(true); // membuka field input

        idCustomerInputTextField.setEnabled(false); // mastikan saja biar tidak dibuka 
        idCustomerInputTextField.setText(cc.generateId()); // membuat ID baru berdasarkan nilai id tertinggi
    }//GEN-LAST:event_tambahCustomerButtonActionPerformed

    private void simpanCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanCustomerButtonActionPerformed
        if (actionCustomer == null) {
            return;
        }
        try {
            inputKosongPelangganException();
            InputHarusAngkaPelangganException();

            int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin "+ actionCustomer +" ?", actionCustomer, JOptionPane.YES_NO_OPTION);
            if (opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION) {
                return;
            }
            
            switch (actionCustomer) {
                case "add":
                    c = new Customer (idCustomerInputTextField.getText(), namaCustomerInputTextfield.getText(), alamatInputTextField.getText(),nomorTeleponInputTextField.getText());
                    cc.insert(c);
                    break;
                case "update":
                    c = new Customer (idCustomerInputTextField.getText(), namaCustomerInputTextfield.getText(), alamatInputTextField.getText(),nomorTeleponInputTextField.getText());
                    cc.update(c);
                    break;
                default:
                    break;
            }
            actionCustomer = null;
        } catch (InputKosongException e) {
            JOptionPane.showMessageDialog(rootPane, e.message());
        } catch (InputHarusAngkaException e2) {
            JOptionPane.showMessageDialog(rootPane, e2.message());
        }
        clearText();
        setCustomerEditDeleteButton(false);
        setComponentsCustomer(false);
        showCustomer();
    }//GEN-LAST:event_simpanCustomerButtonActionPerformed

    private void tabelCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelCustomerMouseClicked
        actionCustomer = "baharui";
        
        tambahCustomerButton.setEnabled(false);
        batalkanCustomerButton.setEnabled(true);
        simpanCustomerButton.setEnabled(true);        
        setCustomerEditDeleteButton(true);
        
        setComponentsCustomer(false);
        
        int clickedRow = tabelCustomer.getSelectedRow();
        TableModel tableModel = tabelCustomer.getModel();
        if (tabelCustomer.getRowSorter() != null) {
            clickedRow = tabelCustomer.convertRowIndexToModel(clickedRow);
        }
        selectedId = tableModel.getValueAt(clickedRow, 0).toString();

        idCustomerInputTextField.setText(tableModel.getValueAt(clickedRow, 0).toString()); 
        namaCustomerInputTextfield.setText(tableModel.getValueAt(clickedRow, 1).toString());
        nomorTeleponInputTextField.setText(tableModel.getValueAt(clickedRow, 2).toString());
        alamatInputTextField.setText(tableModel.getValueAt(clickedRow, 3).toString());
    }//GEN-LAST:event_tabelCustomerMouseClicked

    private void batalkanCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalkanCustomerButtonActionPerformed
        clearText();
        showCustomer();
        setCustomerEditDeleteButton(false);
        setComponentsCustomer(false);
        tambahCustomerButton.setEnabled(true);
        tabelCustomer.clearSelection();
        
    }//GEN-LAST:event_batalkanCustomerButtonActionPerformed

    private void batalkanCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batalkanCustomerButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_batalkanCustomerButtonMouseClicked

    private void namaCustomerInputTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaCustomerInputTextfieldKeyTyped

    }//GEN-LAST:event_namaCustomerInputTextfieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerButtonPanel;
    private javax.swing.JPanel CustomerFormPanel;
    private javax.swing.JLabel alamatInputLabel;
    private javax.swing.JPanel alamatInputPanel;
    private javax.swing.JTextField alamatInputTextField;
    private javax.swing.JButton barukanCustomerButton;
    private javax.swing.JButton batalkanCustomerButton;
    private javax.swing.JButton hapusCustomerButton;
    private javax.swing.JLabel idCustomerInputLabel;
    private javax.swing.JPanel idCustomerInputPanel;
    private javax.swing.JTextField idCustomerInputTextField;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaCustomerInputLabel;
    private javax.swing.JPanel namaCustomerInputPanel;
    private javax.swing.JTextField namaCustomerInputTextfield;
    private javax.swing.JLabel nomorTeleponInputLabel;
    private javax.swing.JPanel nomorTeleponInputPanel;
    private javax.swing.JTextField nomorTeleponInputTextField;
    private javax.swing.JButton searchCustomerInputButton;
    private javax.swing.JLabel searchCustomerInputLabel;
    private javax.swing.JPanel searchCustomerInputPanel;
    private javax.swing.JTextField searchCustomerInputTextField;
    private javax.swing.JButton simpanCustomerButton;
    private javax.swing.JTable tabelCustomer;
    private javax.swing.JButton tambahCustomerButton;
    // End of variables declaration//GEN-END:variables
}
